export { DashboardPage } from './DashboardPage'
export { EmployeePage } from './EmployeePage'
export { SalaryPage } from './SalaryPage'
export { InsurancePage } from './InsurancePage'
export { AttendancePage } from './AttendancePage'
export { TaxPage } from './TaxPage'
export { ReportPage } from './ReportPage'
export { SettingsPage } from './SettingsPage'
